/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package udpm.fpt.form;

import com.raven.datechooser.DateBetween;
import com.raven.datechooser.DateChooser;
import com.raven.datechooser.listener.DateChooserAction;
import com.raven.datechooser.listener.DateChooserAdapter;
import java.awt.Color;
import java.awt.Component;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import static udpm.fpt.Application.getBean;
import udpm.fpt.component.UpdateDelivery;
import udpm.fpt.main.Main;
import udpm.fpt.model.Bill;
import udpm.fpt.model.BillDetails;
import udpm.fpt.model.DeliveryNote;
import udpm.fpt.model.User;
import udpm.fpt.repository.IDelivery_noteRespository;
import udpm.fpt.swing.table.TableCustom;
import udpm.serviceDelivery.MailSender;
import udpm.serviceDelivery.NumberFilter;
import udpm.serviceDelivery.PanelTest;
import udpm.serviceDelivery.Service;

/**
 *
 * @author PHONG PC
 */
public class DeliveryNoteForm2 extends javax.swing.JPanel {

    /**
     * Creates new form DeliveryNoteForm2
     */
    public DeliveryNoteForm2(User user, Main main) {
        initComponents();
        this.user = user;
        this.main = main;
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lbNgayTao = new javax.swing.JLabel();
        lbNgayXuatKho = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lbDiaChi = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lbTenKhachHang = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lbGhiChu = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lbSanPham = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtLoaiVanChuyen = new javax.swing.JLabel();
        lbTienCOD = new javax.swing.JLabel();
        btnBenVanChuyen = new udpm.fpt.swing.ButtonMessage();
        btnDeliveryCompleted = new udpm.fpt.swing.ButtonMessage();
        btnDelete = new udpm.fpt.swing.ButtonMessage();
        btnUpdate = new udpm.fpt.swing.ButtonMessage();
        jLabel1 = new javax.swing.JLabel();
        lblpaymentStatus = new javax.swing.JLabel();
        buttonMessage1 = new udpm.fpt.swing.ButtonMessage();
        txtXapSep = new udpm.fpt.swing.TextField();
        cbbTimKiem = new udpm.fpt.swing.Combobox();
        txtTimKiem = new udpm.fpt.swing.TextField();
        cbbSearchStatus = new udpm.fpt.swing.Combobox();
        jScrollPaneHoaDon = new javax.swing.JScrollPane();
        tblDanhSach2 = new javax.swing.JTable();
        btnSearch = new udpm.fpt.swing.ButtonMessage();
        jButton3 = new udpm.fpt.swing.ButtonMessage();
        progressIndicator1 = new udpm.fpt.progressindicator.ProgressIndicator();

        setPreferredSize(new java.awt.Dimension(1527, 824));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delivery Note", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Detailed Packing List");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel21.setText("Packing Date:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel23.setText("Estimated Date:");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel25.setText("Delivery address");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel26.setText("Customer name:");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel28.setText("Note:");

        jScrollPane4.setBorder(null);

        lbGhiChu.setColumns(20);
        lbGhiChu.setRows(5);
        lbGhiChu.setBorder(null);
        jScrollPane4.setViewportView(lbGhiChu);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Product:");

        jScrollPane5.setBorder(null);

        lbSanPham.setColumns(20);
        lbSanPham.setRows(5);
        lbSanPham.setBorder(null);
        jScrollPane5.setViewportView(lbSanPham);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("Total Amount:");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel29.setText("Shipping Type:");

        btnBenVanChuyen.setBackground(new java.awt.Color(0, 153, 255));
        btnBenVanChuyen.setForeground(new java.awt.Color(255, 255, 255));
        btnBenVanChuyen.setText("Transfer to the shipping department");
        btnBenVanChuyen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBenVanChuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBenVanChuyenActionPerformed(evt);
            }
        });

        btnDeliveryCompleted.setBackground(new java.awt.Color(0, 153, 255));
        btnDeliveryCompleted.setForeground(new java.awt.Color(255, 255, 255));
        btnDeliveryCompleted.setText("Delivery Completed");
        btnDeliveryCompleted.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeliveryCompleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliveryCompletedActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(204, 0, 0));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(0, 153, 255));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Edit Information");
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("payment_status:");

        buttonMessage1.setBackground(new java.awt.Color(0, 153, 255));
        buttonMessage1.setForeground(new java.awt.Color(255, 255, 255));
        buttonMessage1.setText("Delivery");
        buttonMessage1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonMessage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMessage1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTenKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbNgayTao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbNgayXuatKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLoaiVanChuyen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbTienCOD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblpaymentStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addGap(76, 76, 76)
                                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(323, 323, 323)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(btnDeliveryCompleted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 202, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBenVanChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonMessage1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 275, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTenKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(lbNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNgayXuatKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblpaymentStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(lbTienCOD, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addGap(9, 9, 9))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtLoaiVanChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBenVanChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMessage1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeliveryCompleted, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );

        txtXapSep.setLabelText("Order Date");

        cbbTimKiem.setLabeText("Search for");

        txtTimKiem.setLabelText("Search");

        cbbSearchStatus.setLabeText("Status");
        cbbSearchStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbSearchStatusMouseClicked(evt);
            }
        });
        cbbSearchStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbSearchStatusActionPerformed(evt);
            }
        });

        tblDanhSach2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Delivery code", "Bill code", "Waybill_number", "Status", "Transport unit id", "Shipping cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDanhSach2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblDanhSach2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSach2MouseClicked(evt);
            }
        });
        jScrollPaneHoaDon.setViewportView(tblDanhSach2);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jButton3.setText(" Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        progressIndicator1.setBackground(new java.awt.Color(255, 255, 255));
        progressIndicator1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 80, 1, 80));
        progressIndicator1.setForeground(new java.awt.Color(246, 242, 242));
        progressIndicator1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        progressIndicator1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Đang chuẩn bị", "Đã bàn giao", "Đang giao hàng", "Giao thành công" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        progressIndicator1.setProgress(1.0F);
        progressIndicator1.setProgressColorGradient(new java.awt.Color(153, 0, 51));
        progressIndicator1.setProgressFill(true);
        progressIndicator1.setProgressSpaceLabel(6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtXapSep, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(cbbTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE))
                    .addComponent(jScrollPaneHoaDon)
                    .addComponent(progressIndicator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(cbbSearchStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbbTimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbbSearchStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtXapSep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPaneHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progressIndicator1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbbSearchStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbSearchStatusMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbSearchStatusMouseClicked

    private void cbbSearchStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbSearchStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbSearchStatusActionPerformed

    private void tblDanhSach2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSach2MouseClicked
        int row = tblDanhSach2.getSelectedRow();
        if (row == -1) {
            return;
        }
        setFormThongTin(row);
    }//GEN-LAST:event_tblDanhSach2MouseClicked

    private void btnBenVanChuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBenVanChuyenActionPerformed
        int row = tblDanhSach2.getSelectedRow();
        if (row == -1) {
            return;
        }
        Long idDanhSach = Long.valueOf(tblDanhSach2.getValueAt(row, 0).toString());
        Optional<DeliveryNote> list = sv.filById(idDanhSach);
        DeliveryNote deliverynote = list.get();
        deliverynote.setStatus_id(2);
        sv.updateDeliveryNote(idDanhSach, maVanDon, deliverynote);
        loadDataAndFillTableDeli();
        progressIndicator1.setProgress(0);
        this.main.notificationShowSUCCESS("SUCCESS!");
    }//GEN-LAST:event_btnBenVanChuyenActionPerformed

    private void btnDeliveryCompletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliveryCompletedActionPerformed
        int row = tblDanhSach2.getSelectedRow();
        if (row == -1) {
            return;
        }
        Long idDanhSach = Long.valueOf(tblDanhSach2.getValueAt(row, 0).toString());
        Optional<DeliveryNote> list = sv.filById(idDanhSach);
        DeliveryNote deliverynote = list.get();
        deliverynote.setStatus_id(5);
        sv.updateDeliveryNote(idDanhSach, maVanDon, deliverynote);
        sv.updateBill("Paid", deliverynote.getBill_id());
        loadDataAndFillTableDeli();
        progressIndicator1.setProgress(0);
        this.main.notificationShowSUCCESS("SUCCESS!");

    }//GEN-LAST:event_btnDeliveryCompletedActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int row = tblDanhSach2.getSelectedRow();
        if (row == -1) {
            return;
        }
        if (this.deleteDeli()) {
            progressIndicator1.setProgress(0);
            sv.historyRemove("The "+tblDanhSach2.getValueAt(row, 0).toString()+" delivery has been delete", user);
            this.main.notificationShowSUCCESS("SUCCESS!");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int row = tblDanhSach2.getSelectedRow();
        if (row == -1) {
            return;
        }
        Long idDanhSach = Long.valueOf(tblDanhSach2.getValueAt(row, 0).toString());
        for (DeliveryNote deli : listDeli) {
            if (Objects.equals(deli.getId(), idDanhSach)) {
                UpdateDelivery update = new UpdateDelivery(this, idDanhSach, maVanDon, user, main);
                update.setFrom(deli);
                update.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String idStatus;
        String timKiem;
        if (txtTimKiem.getText().trim().isEmpty()) {
            timKiem = "";
        }
        timKiem = txtTimKiem.getText();
        if (cbbSearchStatus.getSelectedIndex() != -1) {
            idStatus = String.valueOf(cbbSearchStatus.getSelectedIndex());
            if (cbbTimKiem.getSelectedIndex() == 0) {
                searchAll(timKiem, "", idStatus.equals("0") ? "" : idStatus);
            } else {
                searchAll("", timKiem, idStatus.equals("0") ? "" : idStatus);
            }
        }
        System.out.println(txtTimKiem.getText());
        System.out.println(cbbSearchStatus.getSelectedIndex());
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        txtXapSep.setText(simple.format(new Date()));
        txtTimKiem.setText("");
        cbbTimKiem.setSelectedIndex(0);
        loadDataAndFillTableDeli();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void buttonMessage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMessage1ActionPerformed
        int row = tblDanhSach2.getSelectedRow();
        if (row == -1) {
            return;
        }
        Long idDanhSach = Long.valueOf(tblDanhSach2.getValueAt(row, 0).toString());
        Optional<DeliveryNote> list = sv.filById(idDanhSach);
        DeliveryNote deliverynote = list.get();
        deliverynote.setStatus_id(3);
        sv.updateDeliveryNote(idDanhSach, maVanDon, deliverynote);
        loadDataAndFillTableDeli();
        this.main.notificationShowSUCCESS("SUCCESS!");
    }//GEN-LAST:event_buttonMessage1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private udpm.fpt.swing.ButtonMessage btnBenVanChuyen;
    private udpm.fpt.swing.ButtonMessage btnDelete;
    private udpm.fpt.swing.ButtonMessage btnDeliveryCompleted;
    private udpm.fpt.swing.ButtonMessage btnSearch;
    private udpm.fpt.swing.ButtonMessage btnUpdate;
    private udpm.fpt.swing.ButtonMessage buttonMessage1;
    private udpm.fpt.swing.Combobox cbbSearchStatus;
    private udpm.fpt.swing.Combobox cbbTimKiem;
    private udpm.fpt.swing.ButtonMessage jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPaneHoaDon;
    private javax.swing.JLabel lbDiaChi;
    private javax.swing.JTextArea lbGhiChu;
    private javax.swing.JLabel lbNgayTao;
    private javax.swing.JLabel lbNgayXuatKho;
    private javax.swing.JTextArea lbSanPham;
    private javax.swing.JLabel lbTenKhachHang;
    private javax.swing.JLabel lbTienCOD;
    private javax.swing.JLabel lblpaymentStatus;
    private udpm.fpt.progressindicator.ProgressIndicator progressIndicator1;
    private javax.swing.JTable tblDanhSach2;
    private javax.swing.JLabel txtLoaiVanChuyen;
    private udpm.fpt.swing.TextField txtTimKiem;
    private udpm.fpt.swing.TextField txtXapSep;
    // End of variables declaration//GEN-END:variables
    private final SimpleDateFormat simple = new SimpleDateFormat("dd-MM-yyyy");
    private String maVanDon = null;
    private final DateChooser datechooser = new DateChooser();
    private final DateChooser datechooser1 = new DateChooser();
    IDelivery_noteRespository delivery = getBean(IDelivery_noteRespository.class);
    private List<DeliveryNote> listDeli = new ArrayList<>();
    private final List<BillDetails> listBillDetail = new ArrayList<>();
    private final List<Bill> listBill = new ArrayList<>();
    private final Service sv = new Service();
    private User user;
    private Main main;

    public void dateChooser() {
        datechooser.setTextField(txtXapSep);
        datechooser.setDateSelectionMode(DateChooser.DateSelectionMode.BETWEEN_DATE_SELECTED);
        datechooser.setLabelCurrentDayVisible(false);
        datechooser.setDateFormat(simple);
        datechooser.addActionDateChooserListener(new DateChooserAdapter() {
            @Override
            public void dateBetweenChanged(DateBetween date, DateChooserAction action) {
                loadDataBetWeenAndFillTableDeli(date.getFromDate(), date.getToDate());
            }
        });
    }

    public void init() {
        cbbSearchFor();
        //loadDataAndFillTableBillDetail();
        loadDataAndFillTableDeli();
        cbbTimKiemTrangThai();
        dateChooser();
        TableCustom.apply(jScrollPaneHoaDon, TableCustom.TableType.DEFAULT);
    }

    public void loadDataAndFillTableDeli() {
        CompletableFuture<List<DeliveryNote>> future = this.sv.loadAsync();
        future.thenAcceptAsync(data -> {
            SwingUtilities.invokeLater(() -> {
                updateTable(data);
                listDeli = data;
            });
        }).exceptionally(throwable -> {
            throwable.printStackTrace(System.out);
            return null;
        });
    }

    public void loadDataBetWeenAndFillTableDeli(Date dateFrom, Date dateTo) {
        CompletableFuture<List<DeliveryNote>> future = this.sv.findBetweenDate(dateFrom, dateTo);
        future.thenAcceptAsync(data -> {
            SwingUtilities.invokeLater(() -> {
                updateTable(data);
            });
        }).exceptionally(throwable -> {
            throwable.printStackTrace(System.out);
            return null;
        });
    }

    private void updateTable(List<DeliveryNote> data) {
        this.listDeli.clear();
        DefaultTableModel tblModel;
        tblModel = (DefaultTableModel) tblDanhSach2.getModel();
        tblModel.setRowCount(0);
        for (DeliveryNote deli : data) {
            BigDecimal bigDecimalValue = new BigDecimal(deli.getShippingCost());
            BigDecimal scaledValue = bigDecimalValue.setScale(3, RoundingMode.HALF_UP);
            tblModel.addRow(new Object[]{
                deli.getId(),
                deli.getBill_id(),
                deli.getWaybill_number(),
                deli.getStatus_id2().getStatusName(),
                deli.getTransport_unit_id2().getTransportUnitName(),
                scaledValue
            });
            this.listDeli.add(deli);
        }
    }

    public boolean deleteDeli() {
        int row = tblDanhSach2.getSelectedRow();
        if (row == -1) {
            return false;
        }
        int hoi = JOptionPane.showConfirmDialog(this, "Bạn muốn xóa phiếu này", "error", JOptionPane.YES_NO_OPTION);
        if (hoi == JOptionPane.YES_OPTION) {
            Long id = Long.valueOf(tblDanhSach2.getValueAt(row, 0).toString());
            delivery.deleteById(id);
            loadDataAndFillTableDeli();
            return true;
        }
        return false;
    }

    public void loadSearch(String search, int row) {
        CompletableFuture<List<DeliveryNote>> future = this.sv.loadSearch(search, row);
        future.thenAcceptAsync(data -> {
            SwingUtilities.invokeLater(() -> {
                updateTable(data);
            });
        }).exceptionally(throwable -> {
            throwable.printStackTrace(System.out);
            return null;
        });
    }

    public void search() {
        String searchTextField = txtTimKiem.getText();
        if (cbbTimKiem.getSelectedIndex() == 1) {
            loadSearch(searchTextField, 1);
        } else {
            loadSearch(searchTextField, 0);
        }
    }

    public void setFormThongTin(int row) {
        Long idPhieu = Long.valueOf(tblDanhSach2.getValueAt(row, 0).toString());
        for (DeliveryNote dl : listDeli) {
            if (Objects.equals(dl.getId(), idPhieu)) {
                lbNgayTao.setText(simple.format(dl.getCreationdate()));
                BigDecimal bigDecimalValue = new BigDecimal(dl.getTotal_amount());
                BigDecimal scaledValue = bigDecimalValue.setScale(3, RoundingMode.HALF_UP);
                lbTienCOD.setText(String.valueOf(scaledValue));
                lbTenKhachHang.setText(String.valueOf(dl.getCustomer_name()));
                lbSanPham.setText(sv.addLineBreak(dl.getMilk_name()));
                lbDiaChi.setText(dl.getAddress());
                lbGhiChu.setText(dl.getNote());
                lbNgayXuatKho.setText(dl.getEstimatedtime() == null ? "" : simple.format(dl.getEstimatedtime()));
                txtLoaiVanChuyen.setText(dl.getTransport_unit_id2().getTransportUnitName());
                maVanDon = dl.getWaybill_number();
                lblpaymentStatus.setText(dl.getBill_id2().getPayment_status());
                if (dl.getStatus_id2().getStatusName().equals("Đang chuẩn bị")) {
                    progressIndicator1.setProgress(0);
                } else if (dl.getStatus_id2().getStatusName().equals("Bàn giao cho bên vận chuyển")) {
                    progressIndicator1.setProgress(1);
                } else if (dl.getStatus_id2().getStatusName().equals("Đang giao hàng")) {
                    progressIndicator1.setProgress(2);
                } else if (dl.getStatus_id2().getStatusName().equals("Giao thành công")) {
                    progressIndicator1.setProgress(3);
                } else if (dl.getStatus_id2().getStatusName().equals("Huỷ giao hàng")) {
                    progressIndicator1.setProgress(-1);
                    progressIndicator1.setOpaque(true);
                }
            }
        }
    }

    public void cbbSearchFor() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbbTimKiem.getModel();
        model.removeAllElements();
        model.addElement("By reference number");
        model.addElement("By customer name");
    }

    public void searchAll(String idDelivery, String customerName, String idStatus) {
        CompletableFuture<List<DeliveryNote>> future = this.sv.SearchAll(idDelivery, customerName, idStatus);
        future.thenAcceptAsync(data -> {
            SwingUtilities.invokeLater(() -> {
                updateTable(data);
            });
        }).exceptionally(throwable -> {
            throwable.printStackTrace(System.out);
            return null;
        });
    }

    public void cbbTimKiemTrangThai() {
        DefaultComboBoxModel cbb = (DefaultComboBoxModel) cbbSearchStatus.getModel();
        cbb.removeAllElements();
        cbb.addElement("Tất cả");
        cbb.addElement("Đang chuẩn bị");
        cbb.addElement("Bàn giao cho bên vận chuyển");
        cbb.addElement("Đang giao hàng");
        cbb.addElement("Huỷ giao hàng");
        cbb.addElement("Giao thành công");
    }
}
