/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package udpm.fpt.form;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import udpm.fpt.model.Sale_Milk1;
import udpm.fpt.servicce.ServiceGGM1;

/**
 *
 * @author Thanh Dat
 */
public class SaleMilkForm extends javax.swing.JPanel {

    /**
     * Creates new form SaleMilk
     */
    public SaleMilkForm() {
        initComponents();
        dtm = (DefaultTableModel) tblgsp.getModel();
        list = sgm.getAll();
        LoadData();
    }
    private DefaultTableModel dtm = new DefaultTableModel();
    private List<Sale_Milk1> list = new ArrayList<>();
    private ServiceGGM1 sgm = new ServiceGGM1();

    /**
     * Creates new form FormSale_Product1
     */
    

   public void LoadData(){
       dtm.setRowCount(0);
       for(Sale_Milk1 sm : this.sgm.getAll()){
           Object[] ob ={
               sm.getID(),
               sm.getSE(),
               sm.getPD(),
               sm.getSD(),
               sm.getED(),
               sm.getMID(),
               sm.getSFID(),
               sm.getCRAT()
           };
           dtm.addRow(ob);
       }
   }

    public Sale_Milk1 getSale_Milk1() {
        Sale_Milk1 sm = new Sale_Milk1();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);

        sm.setID(Integer.parseInt(txtidsp.getText()));
        sm.setSE(txtsesp.getText());
        sm.setPD(Double.parseDouble(txtptg.getText()));
        try {
            sm.setSD(formatter.parse(txtdssp.getText()));
        } catch (Exception e) {
            System.out.println("Err" + e);

        }
        try {
            sm.setED(formatter.parse(txtdesp.getText()));
        } catch (Exception e) {
            System.err.println("Err" + e);
        }
        sm.setMID(Integer.parseInt(txtidsua.getText()));
        sm.setSFID(Integer.parseInt(txtidnvsp.getText()));
//        try {
//            sm.setCRAT(formatter.parse(txtnt.getText()));
//        } catch (Exception e) {
//            System.err.println("Err" + e);
//        }
        return sm;
    }

    public boolean checkifo() {
        if (txtidsp.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin");
            return false;
        } else if (txtsesp.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin");
            return false;
        } else if (txtptg.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin");
            return false;
        } else if (Double.valueOf(txtptg.getText()) > 100) {
            JOptionPane.showMessageDialog(this, "Vui lòng ko nhập quá 100");
            return false;
        } else if (txtdssp.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin");
            return false;
        } else if (txtdesp.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin");
            return false;
        } else if (txtidsua.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin");
            return false;
        } else if (txtidnvsp.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin");
            return false;
        }
//       else if(txtnt.getText().isBlank()){
//           JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin");
//           return false;
//       }

        return true;

    }

    public void timkiemSE(String SE) {
        String timTen = txtsearchsp.getText();
        if (timTen == null) {
            SE = "";
        }
        dtm = (DefaultTableModel) tblgsp.getModel();
        dtm.setRowCount(0);
        for (Sale_Milk1 sm : sgm.timkiem(SE)) {
            Object[] ob = new Object[]{
                sm.getID(),
                sm.getSE(),
                sm.getPD(),
                sm.getSD(),
                sm.getED(),
                sm.getMID(),
                sm.getSFID(),
                sm.getCRAT()
            };
            dtm.addRow(ob);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtdssp = new javax.swing.JTextField();
        txtsesp = new javax.swing.JTextField();
        txtdesp = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtidnvsp = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnaddsp = new javax.swing.JButton();
        btnupdatesp = new javax.swing.JButton();
        btndeletesp = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtidsp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtidsua = new javax.swing.JTextField();
        txtptg = new javax.swing.JTextField();
        txtnt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnclear = new javax.swing.JButton();
        txtsearchsp = new javax.swing.JTextField();
        btnsearchsp = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblgsp = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setText("Sale Event:");

        txtsesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsespActionPerformed(evt);
            }
        });

        txtdesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdespActionPerformed(evt);
            }
        });

        jLabel15.setText("End Date:");

        jLabel16.setText("Percent Decrease:");

        txtidnvsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidnvspActionPerformed(evt);
            }
        });

        jLabel17.setText("Start Date:");

        jLabel18.setText("ID Staff:");

        btnaddsp.setText("Add");
        btnaddsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddspActionPerformed(evt);
            }
        });

        btnupdatesp.setText("Update");
        btnupdatesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdatespActionPerformed(evt);
            }
        });

        btndeletesp.setText("Delete");
        btndeletesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletespActionPerformed(evt);
            }
        });

        jLabel3.setText("ID:");

        jLabel2.setText("ID Milk:");

        txtptg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtptgActionPerformed(evt);
            }
        });

        txtnt.setEditable(false);

        jLabel1.setText("Create Date:");

        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        txtsearchsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchspActionPerformed(evt);
            }
        });

        btnsearchsp.setText("Search");
        btnsearchsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchspActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtptg, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsesp, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtidsp, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdssp, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdesp, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtidsua, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtidnvsp, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnt, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtsearchsp, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(btnaddsp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnupdatesp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btndeletesp)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnclear)
                            .addComponent(btnsearchsp))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtidsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtsesp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtptg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtdssp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtdesp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtidsua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtidnvsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaddsp)
                    .addComponent(btnupdatesp)
                    .addComponent(btndeletesp)
                    .addComponent(btnclear))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsearchsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearchsp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblgsp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Sale Event", "Percent Decrease", "Start Date", "End Date", "ID Milk", "ID Staff", "Create Date"
            }
        ));
        tblgsp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblgspMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblgsp);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Sale For Product");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 483, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtsespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsespActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsespActionPerformed

    private void txtdespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdespActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdespActionPerformed

    private void txtidnvspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidnvspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidnvspActionPerformed

    private void btnaddspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddspActionPerformed
        //        Sale_Milk1 sm = getSale_Milk1();
        //        if (sgm.add(sm)) {
            //            JOptionPane.showMessageDialog(this, "Thêm thành công");
            //        } else {
            //            JOptionPane.showMessageDialog(this, "Thêm thất bại");
            //        }
        //        this.LoadData();
        if (this.checkifo()) {
            Sale_Milk1 sm = getSale_Milk1();
            if (sgm.add(sm)) {
                JOptionPane.showMessageDialog(this, "Thêm thành công");
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
            }
            this.LoadData();
        }
    }//GEN-LAST:event_btnaddspActionPerformed

    private void btnupdatespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdatespActionPerformed
        if (checkifo()) {
            Sale_Milk1 sm = this.getSale_Milk1();
            int id = Integer.valueOf(txtidsp.getText());

            try {
                if (sgm.update(id, sm)) {
                    JOptionPane.showMessageDialog(this, "Sửa thành công");
                    LoadData();
                } else {
                    JOptionPane.showMessageDialog(this, "Sửa thành thất bại");
                    return;
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_btnupdatespActionPerformed

    private void btndeletespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletespActionPerformed
        int row = tblgsp.getSelectedRow();
        boolean sm = sgm.delete(Integer.valueOf(txtidsp.getText()));
        if (sm) {
            JOptionPane.showMessageDialog(this, "Xóa thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
        }
        this.LoadData();
    }//GEN-LAST:event_btndeletespActionPerformed

    private void txtptgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtptgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtptgActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        txtidnvsp.setText("");
        txtsesp.setText("");
        txtptg.setText("");
        txtdssp.setText("");
        txtdesp.setText("");
        txtidsp.setText("");
        txtidsua.setText("");
        txtnt.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void txtsearchspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchspActionPerformed

    private void btnsearchspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchspActionPerformed
        String SE = txtsearchsp.getText();
        this.timkiemSE(SE);
    }//GEN-LAST:event_btnsearchspActionPerformed

    private void tblgspMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblgspMouseClicked
        int row = tblgsp.getSelectedRow();
        if (row == -1) {
            return;
        }
        Sale_Milk1 sm = this.sgm.getAll().get(row);
        txtidsp.setText(tblgsp.getValueAt(row, 0).toString());
        txtsesp.setText(tblgsp.getValueAt(row, 1).toString());
        txtptg.setText(tblgsp.getValueAt(row, 2).toString());
        txtdssp.setText(tblgsp.getValueAt(row, 3).toString());
        txtdesp.setText(tblgsp.getValueAt(row, 4).toString());
        txtidsua.setText(tblgsp.getValueAt(row, 5).toString());
        txtidnvsp.setText(tblgsp.getValueAt(row, 6).toString());

    }//GEN-LAST:event_tblgspMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddsp;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndeletesp;
    private javax.swing.JButton btnsearchsp;
    private javax.swing.JButton btnupdatesp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblgsp;
    private javax.swing.JTextField txtdesp;
    private javax.swing.JTextField txtdssp;
    private javax.swing.JTextField txtidnvsp;
    private javax.swing.JTextField txtidsp;
    private javax.swing.JTextField txtidsua;
    private javax.swing.JTextField txtnt;
    private javax.swing.JTextField txtptg;
    private javax.swing.JTextField txtsearchsp;
    private javax.swing.JTextField txtsesp;
    // End of variables declaration//GEN-END:variables
}
