/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package udpm.fpt.form;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import udpm.fpt.model.Sale_Bill1;
import udpm.fpt.service.ServiceGGB1;

/**
 *
 * @author Thanh Dat
 */
public class SaleBill extends javax.swing.JPanel {

    /**
     * Creates new form Sale
     */
    public SaleBill() {
        initComponents();
        dtm = (DefaultTableModel) tblghh.getModel();
        list = sgb.getAll();
        LoadData();
    }
    private DefaultTableModel dtm = new DefaultTableModel();
    private List<Sale_Bill1> list = new ArrayList<>();
    private ServiceGGB1 sgb = new ServiceGGB1();

    /**
     * Creates new form FormSale_Bill1
     */

    public void LoadData() {
        dtm.setRowCount(0);
        for (Sale_Bill1 sb : this.sgb.getAll()) {
            Object[] ob = {
                sb.getID(),
                sb.getSE(),
                sb.getDC(),
                sb.getPD(),
                sb.getSD(),
                sb.getED(),
                sb.getSFID(),
                sb.getCRAT()
            };
            dtm.addRow(ob);
        }
    }

    public Sale_Bill1 getSale_Bill1() {
        Sale_Bill1 sb = new Sale_Bill1();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);

        sb.setID(Integer.parseInt(txtidhd.getText()));
        sb.setSE(txtsehd.getText());
        sb.setDC(txtdkgghd.getText());
        sb.setPD(Double.parseDouble(txtptg.getText()));
        try {
            sb.setSD(formatter.parse(txtdshd.getText()));
        } catch (Exception e) {
            System.out.println("Err" + e);

        }
        try {
            sb.setED(formatter.parse(txtdehd.getText()));
        } catch (Exception e) {
            System.err.println("Err" + e);
        }
        sb.setSFID(Integer.parseInt(txtidnvhd.getText()));
//        try{
//            sb.setCRAT(formatter.parse(txtnt.getText()));
//        }catch(Exception e){
//            System.err.println("Err" + e);
//        }
        return sb;
    }

    public boolean checkifo() {
        if (txtidhd.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin");
            return false;
        } else if (txtsehd.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin");
            return false;
        } else if (txtdkgghd.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin");
            return false;
        } else if (txtptg.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin");
            return false;
        } else if (Double.valueOf(txtptg.getText()) > 100) {
            JOptionPane.showMessageDialog(this, "Vui lòng ko nhập quá 100");
            return false;
        } else if (txtdshd.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin");
            return false;
        } else if (txtdehd.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin");
            return false;
        } else if (txtidnvhd.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin");
            return false;
        }
//       else if(txtnt.getText().isBlank()){
//           JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin");
//           return false;
//       }

        return true;

    }

    public void timKiemSE(String SE) {
        String timTen = txtsearchhd.getText();
        if (timTen == null) {
            SE = "";
        }
        dtm = (DefaultTableModel) tblghh.getModel();
        dtm.setRowCount(0);
        for (Sale_Bill1 sb : sgb.timkiem(SE)) {
            Object[] ob = new Object[]{
                sb.getID(),
                sb.getSE(),
                sb.getDC(),
                sb.getPD(),
                sb.getSD(),
                sb.getED(),
                sb.getSFID(),
                sb.getCRAT()
            };
            dtm.addRow(ob);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtdshd = new javax.swing.JTextField();
        txtsehd = new javax.swing.JTextField();
        txtdehd = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtidnvhd = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtdkgghd = new javax.swing.JTextField();
        btnaddhd = new javax.swing.JButton();
        btnupdatehd = new javax.swing.JButton();
        btndeletehd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtidhd = new javax.swing.JTextField();
        txtptg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnt = new javax.swing.JTextField();
        btnclear = new javax.swing.JButton();
        txtsearchhd = new javax.swing.JTextField();
        btnsearchhd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblghh = new javax.swing.JTable();

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("Sale Event:");

        txtdehd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdehdActionPerformed(evt);
            }
        });

        jLabel8.setText("Discount Conditions:");

        jLabel9.setText("End Date:");

        jLabel10.setText("Percent Decrease:");

        txtidnvhd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidnvhdActionPerformed(evt);
            }
        });

        jLabel11.setText("Start Date:");

        jLabel12.setText("ID Staff:");

        txtdkgghd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdkgghdActionPerformed(evt);
            }
        });

        btnaddhd.setText("Add");
        btnaddhd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddhdActionPerformed(evt);
            }
        });

        btnupdatehd.setText("Update");
        btnupdatehd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdatehdActionPerformed(evt);
            }
        });

        btndeletehd.setText("Delete");
        btndeletehd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletehdActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        jLabel3.setText("Create Date:");

        txtnt.setEditable(false);

        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        txtsearchhd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchhdActionPerformed(evt);
            }
        });

        btnsearchhd.setText("Search");
        btnsearchhd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchhdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtdshd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtdehd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtidnvhd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtptg, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtidhd, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtsehd, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtdkgghd, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 34, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtsearchhd, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnsearchhd))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnaddhd)
                                .addGap(18, 18, 18)
                                .addComponent(btnupdatehd)
                                .addGap(18, 18, 18)
                                .addComponent(btndeletehd)
                                .addGap(18, 18, 18)
                                .addComponent(btnclear)))
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtidhd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtsehd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtdkgghd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtptg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtdshd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtdehd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtidnvhd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaddhd)
                    .addComponent(btnupdatehd)
                    .addComponent(btndeletehd)
                    .addComponent(btnclear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsearchhd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearchhd))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Sale For Bill");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblghh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Sale Event", "Discount Conditions", "Percent Decrease", "Start Date", "End Date", "ID Staff", "Create Date"
            }
        ));
        tblghh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblghhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblghh);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(389, 389, 389))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtdehdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdehdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdehdActionPerformed

    private void txtidnvhdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidnvhdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidnvhdActionPerformed

    private void txtdkgghdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdkgghdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdkgghdActionPerformed

    private void btnaddhdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddhdActionPerformed
        //            Sale_Bill1 sb = getSale_Bill1();
        //            if(sgb.add(sb)){
            //                    JOptionPane.showMessageDialog(this, "Thêm thành công");
            //            }else{
            //                    JOptionPane.showMessageDialog(this, "Thêm thất bại");
            //            }
        //            this.LoadData();
        if (this.checkifo()) {
            Sale_Bill1 sb = getSale_Bill1();

            if (sgb.add(sb)) {
                JOptionPane.showMessageDialog(this, "Thêm thành công");
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
            }
            this.LoadData();
        }
    }//GEN-LAST:event_btnaddhdActionPerformed

    private void btnupdatehdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdatehdActionPerformed
        if (this.checkifo()) {
            Sale_Bill1 sb = this.getSale_Bill1();
            int id = Integer.valueOf(txtidhd.getText());
            try {
                if (sgb.update(id, sb)) {
                    JOptionPane.showMessageDialog(this, "Sửa thành công");
                    LoadData();
                } else {
                    JOptionPane.showMessageDialog(this, "Sửa thành thất bại");
                    return;
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnupdatehdActionPerformed

    private void btndeletehdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletehdActionPerformed
        int row = tblghh.getSelectedRow();
        boolean sb = sgb.delete(Integer.valueOf(txtidhd.getText()));
        if (sb) {
            JOptionPane.showMessageDialog(this, "Xóa thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
        }
        this.LoadData();
    }//GEN-LAST:event_btndeletehdActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        txtidhd.setText("");
        txtsehd.setText("");
        txtdkgghd.setText("");
        txtptg.setText("");
        txtdshd.setText("");
        txtdehd.setText("");
        txtidnvhd.setText("");
        txtnt.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void txtsearchhdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchhdActionPerformed

    }//GEN-LAST:event_txtsearchhdActionPerformed

    private void btnsearchhdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchhdActionPerformed
        String SE = txtsearchhd.getText();
        this.timKiemSE(SE);
    }//GEN-LAST:event_btnsearchhdActionPerformed

    private void tblghhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblghhMouseClicked
        int row = tblghh.getSelectedRow();
        if (row == -1) {
            return;
        }
        Sale_Bill1 sb = this.sgb.getAll().get(row);
        txtidhd.setText(tblghh.getValueAt(row, 0).toString());
        txtsehd.setText(tblghh.getValueAt(row, 1).toString());
        txtdkgghd.setText(tblghh.getValueAt(row, 2).toString());
        txtptg.setText(tblghh.getValueAt(row, 3).toString());
        txtdshd.setText(tblghh.getValueAt(row, 4).toString());
        txtdehd.setText(tblghh.getValueAt(row, 5).toString());
        txtidnvhd.setText(tblghh.getValueAt(row, 6).toString());
        txtnt.setText(tblghh.getValueAt(row, 7).toString());
    }//GEN-LAST:event_tblghhMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddhd;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndeletehd;
    private javax.swing.JButton btnsearchhd;
    private javax.swing.JButton btnupdatehd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblghh;
    private javax.swing.JTextField txtdehd;
    private javax.swing.JTextField txtdkgghd;
    private javax.swing.JTextField txtdshd;
    private javax.swing.JTextField txtidhd;
    private javax.swing.JTextField txtidnvhd;
    private javax.swing.JTextField txtnt;
    private javax.swing.JTextField txtptg;
    private javax.swing.JTextField txtsearchhd;
    private javax.swing.JTextField txtsehd;
    // End of variables declaration//GEN-END:variables
}
