/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package udpm.fpt.component;

import com.raven.datechooser.DateChooser;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Optional;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import udpm.fpt.form.DeliveryNoteFrom;
import udpm.fpt.model.DeliveryNote;
import udpm.fpt.model.Status;
import udpm.fpt.model.TransportUnit;
import udpm.serviceDelivery.NumberFilter;
import udpm.serviceDelivery.Service;

/**
 *
 * @author PHONG PC
 */
public class UpdateDelivery extends javax.swing.JFrame {

    /**
     * Creates new form UpdateDelivery
     */
    public UpdateDelivery(DeliveryNoteFrom deliveryNoteFrom ,Long idPhieu, String maVanDon) {
        initComponents();
        this.idPhieu = idPhieu;
        this.maVanDon = maVanDon;
        this.deliveryNoteFrom = deliveryNoteFrom;
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtTenKhachHang = new udpm.fpt.swing.TextField();
        txtDiaChi = new udpm.fpt.swing.TextField();
        txtSDT = new udpm.fpt.swing.TextField();
        txtTongTien = new udpm.fpt.swing.TextField();
        textAreaScroll1 = new udpm.fpt.swing.TextAreaScroll();
        txtGhiChu = new udpm.fpt.swing.TextArea();
        cbbDonViGiao = new udpm.fpt.swing.Combobox();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        txtIDHoaDon = new udpm.fpt.swing.TextField();
        txtNgayTao = new udpm.fpt.swing.TextField();
        txtSoLuong = new udpm.fpt.swing.TextField();
        cbbTrangThai = new udpm.fpt.swing.Combobox();
        txtTienPhi = new udpm.fpt.swing.TextField();
        textAreaScroll2 = new udpm.fpt.swing.TextAreaScroll();
        txtTenSanPham = new udpm.fpt.swing.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Thông tin đơn hàng");

        txtTenKhachHang.setLabelText("Customer name");

        txtDiaChi.setLabelText("Delivery address");

        txtSDT.setLabelText("Phone Number");

        txtTongTien.setEditable(false);
        txtTongTien.setLabelText("Cash on delivery");

        textAreaScroll1.setBackground(new java.awt.Color(255, 255, 255));
        textAreaScroll1.setLabelText("Note");

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        textAreaScroll1.setViewportView(txtGhiChu);

        cbbDonViGiao.setLabeText("Type of transport");
        cbbDonViGiao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbDonViGiaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenKhachHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textAreaScroll1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                    .addComponent(cbbDonViGiao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbbDonViGiao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(textAreaScroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Thông tin sản phẩm");

        btnDelete.setText("Cancel");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtIDHoaDon.setEditable(false);
        txtIDHoaDon.setLabelText("Bill code");

        txtNgayTao.setLabelText("Creation date");

        txtSoLuong.setLabelText("Total amount");

        cbbTrangThai.setLabeText("Status");

        txtTienPhi.setLabelText("Shipping code");

        textAreaScroll2.setBackground(new java.awt.Color(255, 255, 255));
        textAreaScroll2.setLabelText("Product name");

        txtTenSanPham.setColumns(20);
        txtTenSanPham.setRows(5);
        textAreaScroll2.setViewportView(txtTenSanPham);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIDHoaDon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtNgayTao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbbTrangThai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtTienPhi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textAreaScroll2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtIDHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textAreaScroll2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(cbbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTienPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbDonViGiaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbDonViGiaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbDonViGiaoActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(this.updateDeliveryNote(idPhieu, maVanDon)) {
            this.dispose();
            this.idPhieu = null;
            deliveryNoteFrom.loadDataAndFillTableDeli();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private udpm.fpt.swing.Combobox cbbDonViGiao;
    private udpm.fpt.swing.Combobox cbbTrangThai;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private udpm.fpt.swing.TextAreaScroll textAreaScroll1;
    private udpm.fpt.swing.TextAreaScroll textAreaScroll2;
    private udpm.fpt.swing.TextField txtDiaChi;
    private udpm.fpt.swing.TextArea txtGhiChu;
    private udpm.fpt.swing.TextField txtIDHoaDon;
    private udpm.fpt.swing.TextField txtNgayTao;
    private udpm.fpt.swing.TextField txtSDT;
    private udpm.fpt.swing.TextField txtSoLuong;
    private udpm.fpt.swing.TextField txtTenKhachHang;
    private udpm.fpt.swing.TextArea txtTenSanPham;
    private udpm.fpt.swing.TextField txtTienPhi;
    private udpm.fpt.swing.TextField txtTongTien;
    // End of variables declaration//GEN-END:variables
public void init() {
        this.setLocationRelativeTo(null);
        ngayTaoDon();
        UnitTranport();
        cbbtrangThai();
        OnlyNumberTextField();
    }
    SimpleDateFormat simple = new SimpleDateFormat("dd-MM-yyyy");
    DateChooser datechooser = new DateChooser();
    Service sv = new Service();
    Long idPhieu = null;
    String maVanDon = null;
    DeliveryNoteFrom deliveryNoteFrom;
    public void ngayTaoDon() {
        datechooser.setTextField(txtNgayTao);
        datechooser.setDateSelectionMode(DateChooser.DateSelectionMode.SINGLE_DATE_SELECTED);
        datechooser.setLabelCurrentDayVisible(false);
    }
    public void setFrom(Optional<DeliveryNote> list) {
        DeliveryNote b = list.get();
        txtTenKhachHang.setText(b.getCustomer_name());
        txtDiaChi.setText(b.getAddress());
        txtSDT.setText(b.getSdt());
        txtTienPhi.setText(String.valueOf(b.getShippingCost()));
        txtIDHoaDon.setText(b.getBill_id2() == null ? "" : String.valueOf(b.getBill_id2().getId()));
        cbbDonViGiao.setSelectedItem(b.getTransport_unit_id2().getTransportUnitName());
        txtTenSanPham.setText(b.getMilk_name());
        txtGhiChu.setText(b.getNote());
        txtNgayTao.setText(simple.format(b.getCreationdate()));
        txtTongTien.setText(String.valueOf(b.getTotal_amount()));
        txtSoLuong.setText(String.valueOf(b.getQuantity()));
        cbbDonViGiao.setSelectedItem(b.getTransport_unit_id2().getTransportUnitName());
        cbbTrangThai.setSelectedItem(b.getStatus_id2().getStatusName());
    }

    public void cbbtrangThai() {
        DefaultComboBoxModel cbb = (DefaultComboBoxModel) cbbTrangThai.getModel();
        cbb.removeAllElements();
        List<Status> listStatus = sv.findAllStatus();
        for (Status st : listStatus) {
            cbb.addElement(st.getStatusName());
        }

    }

    public boolean updateDeliveryNote(Long productId, String maVanDon) {
        String diaChi = txtDiaChi.getText();
        String ghiChu = txtGhiChu.getText();
        String ngayGiao = txtNgayTao.getText();
        String SDT = txtSDT.getText();
        String soLuong = txtSoLuong.getText();
        String tenkhachHang = txtTenKhachHang.getText();
        String tenSanPham = txtGhiChu.getText();
        String tongtien = txtTongTien.getText();
        String tienShip = txtTienPhi.getText();
        String maHoaDon = txtIDHoaDon.getText();
        int donviGiao = cbbDonViGiao.getSelectedIndex() + 1;
        System.out.println(donviGiao);
        int trangThai = cbbTrangThai.getSelectedIndex() + 1;
        try {
            if (sv.updateDeliveryNote(productId, maVanDon, new DeliveryNote(simple.parse(ngayGiao), tenkhachHang, diaChi, Integer.valueOf(maHoaDon),
                    maVanDon, donviGiao, ghiChu,
                    Double.valueOf(tienShip), trangThai, SDT, tenSanPham,
                    Integer.valueOf(soLuong), Double.valueOf(tongtien)))) {
                JOptionPane.showMessageDialog(this, "Update thành công");
                return true;
            } else {
                JOptionPane.showMessageDialog(this, "Update thất bại");
                return true;
            }
        } catch (ParseException ex) {
            ex.printStackTrace();
            return true;
        }
    }

    public void UnitTranport() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) this.cbbDonViGiao.getModel();
        model.removeAllElements();
        List<TransportUnit> tpu = sv.findAllTranportsUnit();
        for (TransportUnit tp : tpu) {
            model.addElement(tp.getTransportUnitName());
        }
    }

    public void OnlyNumberTextField() {
        ((AbstractDocument) txtTienPhi.getDocument()).setDocumentFilter(new NumberFilter());
        ((AbstractDocument) txtSoLuong.getDocument()).setDocumentFilter(new NumberFilter());
        //((AbstractDocument) txtSDT.getDocument()).setDocumentFilter(new NumberFilter() );
        ((AbstractDocument) txtTongTien.getDocument()).setDocumentFilter(new NumberFilter());
    }
}
